---
deployment:
  tasks:
    - export DEPLOYPATH=/home/taromgfk/public_html/
    - /bin/cp -R index.html about.html services.html kind-words.html contact.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
